version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra-container
    ports:
      - "9042:9042"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admin

  redis:
    image: redis
    command: redis-server --requirepass Redis2019!
    #ports:
    # - "6379:6379"

  goapp:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - DB_HOST=cassandra
      - REDIS_HOST=redis
      - APP_WAITFORSTARTUP=60
    #ports:
    # - "8000:8000"
    depends_on:
      - redis
      - cassandra

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - goapp
